export const ACQUISITION_UNIT_POLICY_TYPE = 'ACQ_UNIT';
export const ACQUISITION_UNIT_NON_MEMBER_RESTRICTIVE = 'NON_MEMBER_RESTRICTIVE';
export const ACQUISITION_UNIT_MEMBER_RESTRICTIVE = 'MEMBER_RESTRICTIVE';
export const ACQUISITION_UNIT_MEMBER_NON_RESTRICTIVE = 'MEMBER_NON_RESTRICTIVE';
export const ACQUISITION_UNIT_NON_MEMBER_NON_RESTRICTIVE = 'NON_MEMBER_NON_RESTRICTIVE';
